apiVersion: apps/v1
kind: Deployment
metadata:
  name: jen-app
  labels:
    app: jen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jen
  template:
    metadata:
      labels:
        app: jen
    spec:
      containers:
      - name: jen
        image: wolfix1245/jen:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3005
        env:
        - name: PORT
          value: "3005"
---
apiVersion: v1
kind: Service
metadata:
  name: jen-service
spec:
  selector:
    app: jen
  ports:
  - port: 80
    targetPort: 3005
  type: LoadBalancer